Repository KGU-HouseOfChoi/houseofchoi-FE, pull requests merged in 2025-05, with the labels that each got.

#43 [style]#41 챗봇 하단 스타일 변경 및 마이페이지 버튼 수정
  fe/src/app/member/mypage/page.tsx
  fe/src/components/chatbot/ChatbotHeader.tsx
  fe/src/components/chatbot/layout/ChatbotBottom.tsx
  fe/src/components/chatbot/layout/ChatbotGreeting.tsx
  fe/src/components/chatbot/messages/ChatbotMessageList.tsx
  fe/src/components/mypage/button/FamilyAddButton.tsx
Labels: style, 수빈

#55 [refact]리뷰반영 및 버그수정
  fe/next.config.ts
  fe/package.json
  fe/public/manifest.json
  fe/src/app/auth/page.tsx
  fe/src/app/layout.tsx
  fe/src/app/member/complete/page.tsx
  fe/src/app/member/page.tsx
  fe/src/app/member/personality/page.tsx
  fe/src/components/auth/common/input/FormInput.tsx
  fe/src/components/calendar/CalendarHeader.tsx
  fe/src/components/common/BottomNavBar.tsx
  fe/src/components/family/common/CompletedMessage.tsx
  fe/src/components/family/link/FamilyLinkStep1.tsx
  fe/src/components/home/MainHeader.tsx
  fe/src/components/mypage/button/FamilyAddButton.tsx
Labels: fix, style, refactor, 서희

#56 [fix] input field focus
  .github/pull_request_template.md
  fe/src/components/auth/common/input/BirthdayInput.tsx
  fe/src/components/auth/common/input/FormInput.tsx
  fe/src/components/auth/step/Step5_VerificationCode.tsx
Labels: fix, 서희

#63 [fix] 가족 연동 완료 문구 딜레이 3초로 수정
  fe/src/components/family/link/FamilyLinkStep2.tsx
Labels: fix, 서희

#64 [fix] routing and style
  fe/src/app/member/family/page.tsx
  fe/src/app/member/page.tsx
  fe/src/app/member/personality/page.tsx
  fe/src/components/auth/common/input/BirthdayInput.tsx
  fe/src/components/auth/common/input/FormInput.tsx
  fe/src/components/auth/step/Step5_VerificationCode.tsx
  fe/src/components/family/common/CompletedMessage.tsx
  fe/src/components/family/common/FamilyHeader.tsx
  fe/src/components/family/link/FamilyLinkStep1.tsx
  fe/src/components/family/link/FamilyLinkStep2.tsx
  fe/src/components/home/popup/ActivityInfoPopup.tsx
  fe/src/components/personality/analysis/CompletionNotice.tsx
  fe/src/hooks/auth/useDeleteAccount.ts
Labels: fix, style, refactor, 서희

#65 [feat] 대화를 통한 성향 재분석 기능 및 가족버튼 수정
  fe/src/apis/chatbot/analyzeUserTrait.ts
  fe/src/app/member/mypage/page.tsx
  fe/src/components/chatbot/ChatbotHeader.tsx
  fe/src/components/chatbot/VoiceInput.tsx
  fe/src/components/chatbot/layout/ChatbotBottom.tsx
  fe/src/components/chatbot/messages/ChatbotMessageList.tsx
  fe/src/components/chatbot/popup/VoicePopup.tsx
  fe/src/components/family/popup/FamilyLinkPopup.tsx
  fe/src/components/mypage/button/FamilyAddButton.tsx
  fe/src/hooks/chatbot/useChatbot.ts
  fe/src/hooks/chatbot/useMessageCount.ts
  fe/src/hooks/chatbot/useUserTrait.ts
Labels: feat, 수빈
